services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
    ports:
      - 5432:5432
    networks:
      - postgres-net
networks:
  postgres-net:
    name: postgres-net

    
    
    


